language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.1
bundler_args: --jobs=3 --retry=3 --without development production --deployment
os:
  - linux
  - osx
before_script:
  - RAILS_ENV=test bundle exec rake db:migrate
script:
  - bundle exec rake
