image: ruby:2.3.1
pipelines:
  default:
    - step:
        script:
          - bundle install --deployment --path vendor/bundle
          - bundle exec rake db:migrate
          - bundle exec rake db:test:prepare
          - rake test
