image: ruby:2.3.1
pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y nodejs --no-install-recommends && rm -rf /var/lib/apt/lists/*
          - bundle install --jobs=3 --retry=3 --without development production --deployment --path vendor/bundle
          - RAILS_ENV=test bundle exec rake db:migrate
          - bundle exec rake
