default: &default
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  database: db/development.sqlite3
  <<: *default

test:
  adapter: sqlite3
  database: db/test.sqlite3
  <<: *default

production:
  adapter: postgresql
  encoding: unicode
  database: meet2code_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  <<: *default
